At the market to products' price one needs to pay also additional price of plastic bag.

In [1]:
import torch
import numpy as np

In [2]:
potatoes_kg_ordered = [1,3,7,3,10,6,8,4,3,1,2,0]
tomatoes_kg_ordered = [5,2,3,1,2,3,6,7,3,2,3,1]
prices = [22.37 , 14.45, 26.6, 10.44, 28.49, 24.52, 40.38, 36.51, 18.50, 10.46, 16.51, 4.58]

In [3]:
X = torch.tensor([potatoes_kg_ordered, tomatoes_kg_ordered, torch.ones_like(torch.tensor(potatoes_kg_ordered))])
X

tensor([[ 1,  3,  7,  3, 10,  6,  8,  4,  3,  1,  2,  0],
        [ 5,  2,  3,  1,  2,  3,  6,  7,  3,  2,  3,  1],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [4]:
Y = torch.tensor(prices)
Y

tensor([22.3700, 14.4500, 26.6000, 10.4400, 28.4900, 24.5200, 40.3800, 36.5100,
        18.5000, 10.4600, 16.5100,  4.5800])

In [5]:
X = X.T.float()
X

tensor([[ 1.,  5.,  1.],
        [ 3.,  2.,  1.],
        [ 7.,  3.,  1.],
        [ 3.,  1.,  1.],
        [10.,  2.,  1.],
        [ 6.,  3.,  1.],
        [ 8.,  6.,  1.],
        [ 4.,  7.,  1.],
        [ 3.,  3.,  1.],
        [ 1.,  2.,  1.],
        [ 2.,  3.,  1.],
        [ 0.,  1.,  1.]])

In [6]:
Y = Y.T
Y

tensor([22.3700, 14.4500, 26.6000, 10.4400, 28.4900, 24.5200, 40.3800, 36.5100,
        18.5000, 10.4600, 16.5100,  4.5800])

### Method without gradient computing.

$\hat{\theta} = (X^TX)^{-1} X y$

In [7]:
best_theta = torch.inverse(X.T@X)@X.T@Y

In [8]:
best_theta

tensor([2.0025, 3.9868, 0.5160])

### Metod with gradient computing

In [9]:
params = torch.rand(3, requires_grad=True)
params

tensor([0.3311, 0.9338, 0.0013], requires_grad=True)

In [10]:
lr = 0.01

In [11]:
for epoch in range(300):
  y_pred = X@params
  loss = torch.square(y_pred - Y).mean()
  loss.backward()
  with torch.no_grad():
    params.copy_(params - lr * params.grad)

  print(f"Param values: {params[0]:.5}, {params[1]:.5}, {params[2]:.5}", f"Gradients: {params.grad[0]:.4}, {params.grad[1]:.4},  {params.grad[2]:.4} ")
  params.grad.zero_()

Param values: 2.0471, 2.2429, 0.33863 Gradients: -171.6, -130.9,  -33.74 
Param values: 2.5216, 2.7068, 0.44905 Gradients: -47.45, -46.39,  -11.04 
Param values: 2.6233, 2.9088, 0.48993 Gradients: -10.17, -20.19,  -4.087 
Param values: 2.6153, 3.0262, 0.50906 Gradients: 0.7976, -11.74,  -1.913 
Param values: 2.5773, 3.1132, 0.52102 Gradients: 3.802, -8.707,  -1.196 
Param values: 2.5331, 3.1868, 0.53026 Gradients: 4.418, -7.361,  -0.9244 
Param values: 2.4897, 3.2525, 0.53819 Gradients: 4.334, -6.562,  -0.7931 
Param values: 2.4491, 3.3121, 0.54528 Gradients: 4.061, -5.961,  -0.7084 
Param values: 2.4116, 3.3666, 0.55169 Gradients: 3.75, -5.45,  -0.6416 
Param values: 2.3772, 3.4165, 0.55753 Gradients: 3.447, -4.994,  -0.5835 
Param values: 2.3455, 3.4623, 0.56284 Gradients: 3.163, -4.579,  -0.5313 
Param values: 2.3165, 3.5043, 0.56768 Gradients: 2.901, -4.199,  -0.4838 
Param values: 2.2899, 3.5428, 0.57208 Gradients: 2.661, -3.851,  -0.4403 
Param values: 2.2655, 3.5781, 0.57609 Gra